# Generated by Django 2.1.5 on 2019-02-01 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comment', '0002_auto_20190201_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='uploaded_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
