# Generated by Django 2.1.5 on 2019-02-01 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Comment', '0003_comment_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentlike',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Espn.Profile'),
        ),
    ]
