# Generated by Django 2.1.5 on 2019-01-25 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0002_auto_20190125_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsresource',
            name='resource_url',
            field=models.URLField(),
        ),
    ]
