# Generated by Django 2.1.5 on 2019-01-25 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0004_news_sport_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='sport_type',
            field=models.CharField(choices=[('B', 'Basketball'), ('F', 'Football')], max_length=1),
        ),
    ]
