# Generated by Django 2.1.5 on 2019-01-25 23:00

import News.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0006_auto_20190125_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='background_image',
            field=models.ImageField(blank=True, upload_to=News.models.background_image_path),
        ),
        migrations.AddField(
            model_name='news',
            name='thumbnail_image',
            field=models.ImageField(blank=True, upload_to=News.models.thumbnail_image_path),
        ),
    ]
