# Generated by Django 2.1.5 on 2019-02-01 18:50

import apps.News.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=500)),
                ('news_text', models.TextField()),
                ('sport_type', models.CharField(choices=[('B', 'Basketball'), ('F', 'Football')], max_length=1)),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('thumbnail_image', models.ImageField(blank=True, upload_to=apps.News.models.thumbnail_image_path)),
                ('background_image', models.ImageField(blank=True, upload_to=apps.News.models.background_image_path)),
            ],
            options={
                'verbose_name': 'All News',
                'verbose_name_plural': 'News',
            },
        ),
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_title', models.CharField(blank=True, max_length=256)),
                ('image', models.ImageField(upload_to=apps.News.models.image_path)),
                ('image_description', models.CharField(blank=True, max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='News.News')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
        ),
        migrations.CreateModel(
            name='NewsResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_title', models.CharField(max_length=100)),
                ('resource_url', models.URLField()),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='News.News')),
            ],
        ),
        migrations.CreateModel(
            name='NewsTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_type', models.CharField(choices=[('G', 'Game'), ('T', 'Team'), ('P', 'Player'), ('L', 'League')], max_length=1)),
                ('tagged_id', models.IntegerField()),
                ('tag_title', models.CharField(max_length=40)),
                ('news', models.ManyToManyField(blank=True, to='News.News')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
    ]
