# Generated by Django 2.1.5 on 2019-01-25 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_type', models.CharField(choices=[('G', 'Game'), ('T', 'Team'), ('P', 'Player'), ('L', 'League')], max_length=1)),
                ('tagged_id', models.IntegerField()),
                ('tag_title', models.CharField(max_length=40)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.News.News')),
            ],
        ),
        migrations.AlterField(
            model_name='newsresource',
            name='resource_title',
            field=models.CharField(max_length=100),
        ),
    ]
