# Generated by Django 2.1.5 on 2019-01-31 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newstag',
            name='news',
        ),
        migrations.AddField(
            model_name='newstag',
            name='news',
            field=models.ManyToManyField(to='News.News'),
        ),
    ]
