# Generated by Django 2.1.5 on 2019-02-01 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0002_auto_20190201_0539'),
        ('News', '0003_auto_20190131_2137'),
    ]

    operations = [
    ]
