# Generated by Django 2.1.5 on 2019-01-25 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0005_auto_20190125_1425'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'All News', 'verbose_name_plural': 'News'},
        ),
        migrations.AlterModelOptions(
            name='newsimage',
            options={'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
        migrations.AlterModelOptions(
            name='newstag',
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
    ]
