# Generated by Django 2.1.5 on 2019-01-27 12:34

import Espn.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Espn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='access_token',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to=Espn.models.profile_picture_path),
        ),
    ]
