# Generated by Django 2.1.5 on 2019-02-01 18:50

import apps.Espn.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('profile_picture', models.ImageField(blank=True, upload_to=apps.Espn.models.profile_picture_path)),
                ('access_token', models.CharField(blank=True, max_length=256)),
                ('forget_password_access_token', models.CharField(blank=True, max_length=256)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
