# Generated by Django 2.1.5 on 2019-02-01 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Espn', '0005_profile_active'),
        ('Espn', '0004_auto_20190201_0539'),
    ]

    operations = [
    ]
