# Generated by Django 2.1.5 on 2019-02-01 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('League', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('CORNER', 'corner'), ('HAND', 'hand')], max_length=100)),
                ('time', models.TimeField()),
                ('explanation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_f', models.IntegerField(default=0)),
                ('score_s', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('sport_type', models.CharField(choices=[('BASKET', 'basketball'), ('FOOT', 'football')], max_length=10)),
                ('row_tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='League.RowTournament')),
            ],
        ),
        migrations.CreateModel(
            name='MediaImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Game.Match')),
            ],
        ),
        migrations.CreateModel(
            name='MediaVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Game.Match')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, unique=True)),
                ('sport_type', models.CharField(choices=[('BASKET', 'basketball'), ('FOOT', 'football')], max_length=10)),
                ('post', models.CharField(choices=[('ATTACK', 'attack'), ('DEFENCE', 'defence'), ('GOAL', 'goal keeper')], max_length=100)),
                ('born', models.DateField()),
                ('experience', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('explain', models.TextField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Game.Match')),
            ],
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField(unique=True)),
                ('GP', models.IntegerField()),
                ('MPG', models.IntegerField()),
                ('FG', models.IntegerField()),
                ('APG', models.IntegerField()),
                ('RPG', models.IntegerField()),
                ('BLKPG', models.IntegerField()),
                ('STPG', models.IntegerField()),
                ('PFPG', models.IntegerField()),
                ('PPG', models.IntegerField()),
                ('player', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Game.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, unique=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Game.Match')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='League.TeamResult')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='Game.Team'),
        ),
        migrations.AddField(
            model_name='event',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Game.Match'),
        ),
        migrations.AddField(
            model_name='event',
            name='related_player',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='Game.Player'),
        ),
    ]
